---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4

suites:
  - name: node-01
    run_list:
      - role[vagrant]
      - role[serf-cluster]
    driver:
      network:
        - ["private_network", {ip: "192.168.33.33"}]

  - name: node-02
    run_list:
      - role[vagrant]
      - role[serf-cluster]
    driver:
      network:
        - ["private_network", {ip: "192.168.33.34"}]

